### ISSUE TITLE
Create new page for registrations (link navbar registration button to land on new page)

### ISSUE THREAD

**Issue by devinllu** [richardm1645/HYTE#4]
![Screen Shot 2023-09-07 at 9 44 43 AM](https://github.com/richardm1645/HYTE/assets/43360976/65cd3394-3d1c-41f0-ac80-90faa6b05fff)

Currently, the registration link in the navbar is set to redirect the user to the registration section below on the home page.

Create a new component page for registrations and set the navbar link to redirect the user to /registration endpoint

**Comment by richardm1645** [comment]
New registration component created, the link should redirect to a separate page now
