### ISSUE TITLE
Mentor rows mis-aligned +  overlapping into footer

### ISSUE THREAD

**Issue by devinllu** [richardm1645/HYTE#6]
![Screen Shot 2023-09-12 at 11 46 34 PM](https://github.com/richardm1645/HYTE/assets/43360976/31857b59-6a4b-4434-a43d-02493f2bead2)

- mentor rows not aligned with other rows, as demonstrated for example by Liam picture being more to the right than Alex above him.
- additionally, rows are overlapping into footer. could possibly set "bottom: 0" property in .founder-container class, but then it removes the header

**Comment by richardm1645** [comment]
Fixed avatars display. Max 3 rows, can have any number of mentors on each row now, changed resolution of the background image to resolve it.
